import PDFDocument from 'pdfkit';
import { Readable } from 'stream';

export interface PDFExportOptions {
  title: string;
  slug: string;
  qrPngBuffer: Buffer;
  publicUrl: string;
  destinations?: Array<{ title: string; url: string }>;
  style: {
    fgColor: string;
    bgColor: string;
    ecc: string;
    quietZone: number;
  };
}

/**
 * Generate a PDF spec sheet for a QR code
 */
export async function generateQRPDF(options: PDFExportOptions): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    const doc = new PDFDocument({
      size: 'LETTER',
      margins: {
        top: 72,
        bottom: 72,
        left: 72,
        right: 72,
      },
    });

    // Collect chunks
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Title
    doc.fontSize(24).font('Helvetica-Bold').text(options.title, { align: 'center' });
    doc.moveDown(0.5);

    // Metadata
    doc.fontSize(10).font('Helvetica').fillColor('#666666');
    doc.text(`Slug: ${options.slug}`, { align: 'center' });
    doc.text(`Public URL: ${options.publicUrl}`, { align: 'center' });
    doc.moveDown(1);

    // QR Code image
    const qrSize = 300;
    const pageWidth = doc.page.width;
    const qrX = (pageWidth - qrSize) / 2;
    doc.image(options.qrPngBuffer, qrX, doc.y, {
      width: qrSize,
      height: qrSize,
    });
    doc.moveDown(qrSize / 72 + 1);

    // Technical specifications
    doc.fontSize(14).font('Helvetica-Bold').fillColor('#000000');
    doc.text('Technical Specifications', { underline: true });
    doc.moveDown(0.5);

    doc.fontSize(10).font('Helvetica');
    doc.text(`Error Correction Level: ${options.style.ecc}`);
    doc.text(`Quiet Zone: ${options.style.quietZone} modules`);
    doc.text(`Foreground Color: ${options.style.fgColor}`);
    doc.text(`Background Color: ${options.style.bgColor}`);
    doc.moveDown(1);

    // Destinations
    if (options.destinations && options.destinations.length > 0) {
      doc.fontSize(14).font('Helvetica-Bold');
      doc.text('Destinations', { underline: true });
      doc.moveDown(0.5);

      doc.fontSize(10).font('Helvetica');
      options.destinations.forEach((dest, index) => {
        doc.font('Helvetica-Bold').text(`${index + 1}. ${dest.title}`, { continued: false });
        doc.font('Helvetica').fillColor('#666666').text(`   ${dest.url}`);
        doc.fillColor('#000000');
        doc.moveDown(0.3);
      });
    }

    // Footer - Print guidance
    doc.moveDown(2);
    doc.fontSize(8).fillColor('#999999');
    doc.text(
      'Print guidance: Maintain minimum size of 2cm × 2cm for reliable scanning. Use high-quality printer settings for best results.',
      { align: 'center' }
    );
    doc.text('Generated by QR-Gen Studio', { align: 'center' });

    // Finalize
    doc.end();
  });
}

/**
 * Convert Buffer to Readable stream (helper for some PDF operations)
 */
export function bufferToStream(buffer: Buffer): Readable {
  const stream = new Readable();
  stream.push(buffer);
  stream.push(null);
  return stream;
}

